// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataBaseFirst.Entities;

public partial class Department
{
    [StringLength(50)]
    public string Dname { get; set; }

    [Key]
    public int Dnum { get; set; }

    [Column("MGRSSN")]
    public int? Mgrssn { get; set; }

    [Column("MGRStart Date", TypeName = "datetime")]
    public DateTime? MgrstartDate { get; set; }

    [InverseProperty("DnoNavigation")]
    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

    [ForeignKey("Mgrssn")]
    [InverseProperty("Departments")]
    public virtual Employee MgrssnNavigation { get; set; }
}