// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace task2_createDBwizard.Entities;

public partial class Department
{
    public string Dname { get; set; }

    public int Dnum { get; set; }

    public int? Mgrssn { get; set; }

    public DateTime? MgrstartDate { get; set; }

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

    public virtual Employee MgrssnNavigation { get; set; }
}