// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace task2_createDBwizard.Entities;

public partial class Employee
{
    public string Fname { get; set; }

    public string Lname { get; set; }

    public int Ssn { get; set; }

    public DateTime? Bdate { get; set; }

    public string Address { get; set; }

    public string Sex { get; set; }

    public int? Salary { get; set; }

    public int? Superssn { get; set; }

    public int? Dno { get; set; }

    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();

    public virtual Department DnoNavigation { get; set; }

    public virtual ICollection<Employee> InverseSuperssnNavigation { get; set; } = new List<Employee>();

    public virtual Employee SuperssnNavigation { get; set; }
    public override string ToString()
    {
        return $"ID :{Ssn}\t FullName: {Fname} {Lname}";
    }
}