// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using DataBaseFirst.Entities;
using Microsoft.EntityFrameworkCore;

namespace DataBaseFirst.Context;

public partial class Company_SDContext : DbContext
{
    public Company_SDContext()
    {
    }

    public Company_SDContext(DbContextOptions<Company_SDContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=Company_SD;Integrated Security=True;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Department>(entity =>
        {
            entity.Property(e => e.Dnum).ValueGeneratedNever();

            entity.HasOne(d => d.MgrssnNavigation).WithMany(p => p.Departments).HasConstraintName("FK_Departments_Employee");
        });

        modelBuilder.Entity<Employee>(entity =>
        {
            entity.Property(e => e.Ssn).ValueGeneratedNever();

            entity.HasOne(d => d.DnoNavigation).WithMany(p => p.Employees).HasConstraintName("FK_Employee_Departments");

            entity.HasOne(d => d.SuperssnNavigation).WithMany(p => p.InverseSuperssnNavigation).HasConstraintName("FK_Employee_Employee");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}